### ISSUE TITLE
Handle app.json file

### ISSUE THREAD

**Issue by jimmypoulsen** [pmbanugo/heroku-review-app-actions#4]
When trying to deploy I receive a `KeyError: key not found: "SOME_ARBITRARY_CONFIG_VAR_HERE"` in my build log. I guess this is because you don't handle the app.json file? In our project we have a lot of config variables that our application needs.

Can you think of a way to extract the config variables from the app.json file or do you have a workaround?

**Comment by pmbanugo** [comment]
Did you already set this config on Heroku using something like `heroku config:set` or from the UI?

**Comment by amessinger** [comment]
That might explain the `Redis::CannotConnectError` I get during the setup of the asset pipeline since the Redis addon requirement is declared in my `app.json` file.

**Comment by pmbanugo** [comment]
@amessinger Yeah that's the article I have open as well. I'll check on it later but if you find a solution, feel free to send a PR 🙏🏽

**Comment by pmbanugo** [comment]
Hey @jimmypoulsen @amessinger I've made some enhancement. Can you pls try it out using this version `pmbanugo/heroku-review-app-actions@v1.2.0-dev` 

Let me know if it works well for you. The only new thing you need to do is pass a `use-app-json: true` as an input parameter. E.g:

```yaml
on:
  pull_request:
    types: [opened, reopened, closed, synchronize]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to test custom actions
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy app action step
        uses: pmbanugo/heroku-review-app-actions@v1.2.0-dev
        # uses: ./actions-composite
        id: deploy
        with:
          api-key: ${{ secrets.HEROKU_API_KEY }}
          pipeline-id: ${{ secrets.HEROKU_PIPELINE_ID }}
          app-name-prefix: getting-started
          region: eu
          # stack: heroku-18
          use-app-json: true
      # Use the output from the `deploy` step
      - name: Get the output url
        run: echo "The URL is ${{ steps.deploy.outputs.url }}"
      - name: Comment on commit
        uses: phulsechinmay/rewritable-pr-comment@v0.2.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMENT_IDENTIFIER: "Deploy"
          message: |
            I deployed a review app for you to try out this pull request 👇🏽

            Heroku App: ${{ steps.deploy.outputs.url }}
```
